#Numpy basics

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array((2,3,5))
print(a)
#output 
# [1,2,3,4,5]

type(a)
# output
#numpy.ndarray

# We can see the data type inside this arrays generated by numpy
a.dtype()
#output
#dtype('int32')

# we can set the dtype in our np.array, just like that. 

a = np.array([1,2,3,4,5],dtype='i') # that means the dtype is integer
b = np.array([1,2,3,4,5],dtype='f') # that means the dtype is float

# ================ Multidimensionals arrays ===========================

# we can create multidimentionals arrays, that means list of list using numpy

# !IMPORTANT the arrays need to have the same size to recognize the dimensions, like c array just down there

c = np.array([[1,2,3],[4,5,6]])

# we can see the dimensions size of the array, just like that

c.ndim  # the output of that is 2, because we have 2 dimensions.add()

# If we need a selected info of our array, we can access to the info like that.add()

c[0,2] # we access to the first array and the third element of this array, that means our output is 3 [1,2,3]

# other example with more dimentions

d = np.array([[[1,2,3], [4,5,6], [0,0,-1]], [[-1,-2,-3], [-4,-5,-6], [0,0,1]]])

# we need to access to the second dimention, first array of that dimention and thrid element of that array

d[1,0,2]

# that returns -3 value